version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: api
    volumes:
      - .:/app:cached

  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ".:/app"

  mysql:
    image: mysql:5.6
    env_file:
      - .env.dev
    container_name: mysql
    ports:
      - 33066:3306
